#
# Boosters
# by Auxilor
#

# Even if eco is set up to use a database, you can
# force Boosters to save to local storage to disable
# cross-server sync.
use-local-storage: false

gui:
  title: Boosters
  rows: 3
  mask:
    items:
      - black_stained_glass_Pane
    pattern:
      - "111111111"
      - "101101101"
      - "111111111"
